name: "edit-n2n"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0
 
data_type: "gs-load"
data:
  batch_size: 1
  source: ???
  max_view_num: 96
  eval_camera_distance: 4.0
  camera_distance_range: [1.5, 4.0]
  light_sample_strategy: "dreamfusion3dgs"
  height: 512
  width: 512

  elevation_view_num: 2
  azimuth_view_num: 8
  # elevation_range: [-10 , 80]
system_type: "gsedit-system-edit-adss"
system:
  gs_source: ???
  per_editing_step: 10
  edit_begin_step: 0
  densify_until_iter: 200000
  densify_from_iter: 0
  densification_interval: 100
  max_grad: 5
  min_opacity: 0.005
  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    prompt: 'a bicycle parked next to a bench in a park, all covered with snow, winter'

  guidance_type: "stable-diffusion-instructpix2pix-guidance"
  guidance:
    min_step_percent: 0.02
    max_step_percent: 0.98
    guidance_scale: 7.5
    condition_scale: 1.5
  adss:
    ts_img_size: 512
    ts_caption: 'A man standing in front of a concrete wall. face. hair. sweater'
    ts_blip_type: "large"
    ts_layer_num: 6
    ts_blur: True
    ts_thresh: 150
    ts_model_type: 'vit_h'
    ts_sam_checkpoint: 'CACHE_DIR/sam_vit_h_4b8939.pth'
    ts_use_default_sam: True
    ts_points_per_side: 8
    ts_pred_iou_thresh: 0.99
    ts_stability_score_thresh: 0.95
    ts_crop_n_layers: 0
    ts_crop_n_points_downscale_factor: 1
    ts_min_mask_region_area: 0
    ts_SAM_masks_filter_thresh: 0.9
    ts_min_area: 200
    ts_use_mobilesam: False
    ts_mobilesam_model_type: 'vit_t'
    ts_mobilesam_ckpt: "null"
    erode_kernel_size: 10
    dilate_kernel_size: 10
    failed_seg_idx_list: ""
    saved_dir: "results/results"
    ts_query: "face"
    erode_mask: False
    dilate_mask: True
    smooth_mask: True
    gaussian_filter_ratio: 0.01
    mask_flip: True


  loggers:
    wandb:
      enable: false
      project: 'threestudio_gs'
      name: None

  loss:
#    lambda_opaque: 0.0
    lambda_sparsity: 0.0
    lambda_opaque: 0.0
    lambda_l1: 10.
    lambda_p: 10.
    lambda_dds: 0.
    lambda_anchor_color: 5
    lambda_anchor_geo: 50
    lambda_anchor_opacity: 50
    lambda_anchor_scale: 50
    lambda_move: 0
    lambda_alpha: 0
    lambda_scale: 0

  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 20
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

# white_background: true